image: golang:1.15.8-alpine3.12

stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  script:
    - go build

unit_tests:
  stage: test
  script:
    - CGO_ENABLED=0 go test -v ./... -coverprofile=unit_coverage.out -tags=unit

lint:
  image: golangci/golangci-lint:v1.27.0
  stage: lint
  allow_failure: true
  script:
    - golangci-lint run -v

docker_build_and_deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"